### ISSUE TITLE
NhostApolloProvider Limitation

### ISSUE THREAD

**Issue by ssengalanto** [nhost/react-apollo#1]
Is there a way to pass custom cache settings, because I'm using reactive variables and upon checking the code on how NhostApolloProvider works it seems that I can't pass any customization, the cache defaults to `new _apolloCacheInmemory.InMemoryCache()` without an option to pass any args

`  var client = new _client.ApolloClient({
    ssr: ssr,
    link: (0, _apolloLink.from)([link]),
    cache: new _apolloCacheInmemory.InMemoryCache(),
    defaultOptions: {
      watchQuery: {
        fetchPolicy: "cache-and-network"
      }
    }
  });`

**Comment by elitan** [comment]
Fixed in https://github.com/nhost/react-apollo/pull/2
