### ISSUE TITLE
ApolloClient does not support headers that need to be set after it's already initialized by NhostApolloProvider

### ISSUE THREAD

**Issue by ctrlemo** [nhost/react-apollo#25]
The Nhost generated ApolloClient takes into account headers that are being passed in as props at the moment of initialization through NhostApolloProvider.

The authLink sets these headers through getAuthHeaders().

But authLink does not consider headers that might need to be set at a later point in time through the use of setContext. It ignores the previousContext. Here is an example.
https://www.apollographql.com/docs/react/networking/authentication/#header

Here is an example of how a developer might want to create additional Apollo Links and chain them.
`
  const apolloClient = useApolloClient();

        const setCustomAuthLink = setContext((request, previousContext) => {
          return {
            headers: {
              ...(previousContext?.headers || {}),
              authorization: `Bearer ${accessToken}`,
            },
          };
        });

  apolloClient.setLink(from([setCustomAuthLink, apolloClient.link]));
`
since NhostApolloProvider already created a ApolloClient link, we need to grab it from the client and place it at the end of the new array of links, preceded by any additional links we might want to add.

**Comment by elitan** [comment]
closed in https://github.com/nhost/react-apollo/pull/26
