### ISSUE TITLE
Impossible to add or override extra headers when making requests (required to select role)

### ISSUE THREAD

**Issue by niieani** [nhost/react-apollo#27]
It is currently impossible to add or override extra headers when making requests with `@nhost/react-apollo`. I had to patch the package as follows to make it possible:

```diff
diff --git a/node_modules/@nhost/react-apollo/lib/cjs/index.js b/node_modules/@nhost/react-apollo/lib/cjs/index.js
index beac785..323a9c8 100644
--- a/node_modules/@nhost/react-apollo/lib/cjs/index.js
+++ b/node_modules/@nhost/react-apollo/lib/cjs/index.js
@@ -67,9 +67,9 @@ function generateApolloClient({ nhost, graphqlUrl, headers, publicRole, fetchPol
     const httplink = (0, client_1.createHttpLink)({
         uri,
     });
-    const authLink = (0, context_1.setContext)(() => {
+    const authLink = (0, context_1.setContext)((operation, prevContext) => {
         return {
-            headers: Object.assign({}, getAuthHeaders()),
+            headers: Object.assign({}, prevContext?.headers ?? {}, getAuthHeaders()),
         };
     });
     const link = wsLink
```

Without this patch, it's impossible to send GraphQL requests as a different role.

**Comment by ctrlemo** [comment]
Hi @niieani , thanks for your feedback.
But the same issue was reported and PR'd and fixed a few days ago here
#25

**Comment by ctrlemo** [comment]
The fix is in the latest release https://github.com/nhost/react-apollo/releases/tag/v2.1.0

**Comment by niieani** [comment]
Ah lovely, thanks @ctrlemo! I've originally reported this on Discord, and the other ticket didn't exist then. It just took me a while to actually write an issue.
